[package]
name = "rgb-lib-stress-test"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
rand = "0.8.5"
rgb-lib = "0.2.2"

[patch.crates-io]
rgb-lib = { git = "https://github.com/RGB-Tools/rgb-lib", branch = "stress_test_v0.10" }
